wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: huggingface
    huggingface_version: 4.16.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.5
    start_time: 1660840666
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      3:
      - 16
      - 23
      4: 3.8.5
      5: 0.12.10
      6: 4.16.2
      8:
      - 2
      - 5
act_fn:
  desc: null
  value: torch.nn.modules.activation.GELU
batch_size:
  desc: null
  value: 64
blocks_types:
  desc: null
  value: resnet
channels:
  desc: null
  value: 128
criterion:
  desc: null
  value: null
csv_path:
  desc: null
  value: /home/konradkaranowski/SDU_Project/data_split_to_dirs.csv
dataset:
  desc: null
  value: PneumoniaDataModule
dropout_pb:
  desc: null
  value: 0.3
in_channels:
  desc: null
  value: 1
lr_scheduler:
  desc: null
  value: ReduceLROnPlateau
model:
  desc: null
  value: null
n_blocks:
  desc: null
  value: 10
n_classes:
  desc: null
  value: 2
optim_hparams/lr:
  desc: null
  value: 0.0001
optim_hparams/weight_decay:
  desc: null
  value: 1.0e-05
optimizer:
  desc: null
  value: AdamW
out_channels:
  desc: null
  value: 64
test_size:
  desc: null
  value: 440
train_size:
  desc: null
  value: 1496
val_size:
  desc: null
  value: 264
